name: Deploy to ECS

# This workflow will only run when manually triggered.
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'

    - name: Deploy to ECS
      working-directory: ./backend
      run: |
        echo "Deploying to ECS Cluster..."
        aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment
