name: Deploy SPA

on:
  push:
    paths: ['spa/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        working-directory: ./spa

    - name: Install dependencies
      run: npm install
      working-directory: ./spa

    - name: Build the app
      run: npm run build
      working-directory: ./spa

    - name: Upload to S3
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      working-directory: ./spa
